export const FETCH_USER = 'fetch_user';
export const FETCH_SITES = 'FETCH_SITES';
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_ZONES = 'FETCH_ZONES';
export const FETCH_SITE_LOCATIONS = 'FETCH_SITE_LOCATIONS';
export const FETCH_LOCATION_ZONES = 'FETCH_LOCATION_ZONES';
export const FETCH_LOCATION_CHARTS = 'FETCH_LOCATION_CHARTS';
